---
title: "EDLD Lab-1"
author: 
  - "Anisha"
  - "Shijing "
date: "1/13/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r }
knitr::opts_chunk$set(message = FALSE)
```

``` {r setup}
library(here)
library(lubridate)
library(tidyverse)
library(ggridges)

rstats_tweets <- readRDS(here("data", "rstats_tweets.rds"))
```

```{r plot 1}
# because you've loaded the tidyverse, there's not need to use
# namespacing
screen_name_count <- 
  rstats_tweets %>% 
  count(screen_name)

# Note that `top_n()` has been superseded by `slice_max()`.
# But actually if you sort first, as you have here, you could
# just use `slice(1:25)`.

screen_name_count <-
  screen_name_count %>% 
  arrange(desc(n)) %>% 
  top_n(25, n)

# rough plot 
screen_name_count %>% 
  ggplot(aes(reorder(screen_name, n), n)) + 
  geom_col() + 
  coord_flip()

# final plot
screen_name_count %>% 
  ggplot(aes(reorder(screen_name, n), n)) + 
  geom_col(color = "white", 
           fill = "cornflowerblue",
           alpha = 0.9) + 
  labs(title = "Most prolific #rstats tweeters",
       subtitle = "Top 25 screen names displayed",
       x = "Twitter Screen Name",
       y ="Count",
       caption = "Data from Mike Kearny, distributed via #tidytuesday") +
  theme(panel.grid.major.x = element_line(color = "grey"),
        panel.background = element_rect(fill = NA)) +
  scale_y_continuous(expand = c(0,0)) +
  coord_flip()
# Nice!
```

```{r plot 2}
# Removed namespacing, because luridate was already loaded
# create new variable
rstats_tweets2 <- rstats_tweets %>%
  select(created_at) %>%
  mutate(months = round_date(created_at, unit = "month")) 

# rough plot
rstats_tweets2 %>%
  count(months) %>%
  ggplot(aes(x = months, y = n)) +
  geom_line() +
  geom_smooth() +
  scale_x_datetime(limits = as.POSIXct(c("2008-09-01 00:00:00","2018-12-12 00:00:00")))

# The geom_ridgeline is interesting. I've shown below how to do the same thing 
# with `geom_ribbon()`. Also it looks like you forgot to limit the x-axis on 
# this one. I've shown an alternative approach below.

# final plot
rstats_tweets2 %>%
  count(months) %>%
  filter(months < as_datetime("2019-01-01 00:00:00")) %>% 
  ggplot(aes(x = months, y = n)) +
  # geom_ridgeline(aes(x = months, y = 0, height = n), 
  #                color = 'gray40', fill = 'steelblue1', alpha = 0.5) +
  geom_ribbon(aes(ymin = -Inf, ymax = n),
              color = "gray40",
              fill = "steelblue1", 
              alpha = 0.5) +
  geom_smooth(se = FALSE, color = 'maroon2') +
  theme_minimal() +
  labs(x = "Year (data summarized by month",
       y = "Number of #rstats tweets",  
       title = "Growth of the #rstats hashtag on twitter over time",
       caption = "Data from Mike Kearney, distributed via #tidytuesday")

```




